name: CI/CD
on:
  pull_request:
  push:
    branches: [master, auth]
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # Для сборки микросервисов
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      # Для сборки фронта
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: cd frontend && npm install && npm run build

      # - name: Build auth service
      #   run: cd auth-service && make build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_YANDEX_CLOUD_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: GITHUB_TOKEN
          script: |
            set -e
            cd /home/${{ secrets.SSH_USER }}/bull-run
            
            git stash push -u -m "Auto-stash $(date +%Y-%m-%d_%H:%M:%S)"
            
            ORIGINAL_ORIGIN=$(git remote get-url origin)
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/marcho4/bull-run.git
            git fetch origin master
            git reset --hard origin/master
            git remote set-url origin "$ORIGINAL_ORIGIN"
            
            docker compose build
            
            docker compose up -d --force-recreate --no-build
            
            docker image prune -f
            docker compose ps
